namespace: prod

image:
  repository: abhinavbabu33/new-shopnova-order
  tag: latest
  pullPolicy: Always

replicaCount: 1

port: 8003

resources:
  requests:
    cpu: 128m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  nodeEnv: production
  configMapName: shopnova-config
  secretName: shopnova-secrets
  notificationServiceHost: notification-service
  notificationServicePort: "8004"
