# Order Service — values.yaml
namespace: prod

image:
  repository: abhinavbabu33/shopnova-order-service
  tag: latest
  pullPolicy: Always

replicaCount: 1

port: 8003

resources:
  requests:
    cpu: 128m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Environment — non-sensitive (sourced from ConfigMap)
env:
  nodeEnv: production
  configMapName: shopnova-config
  secretName: shopnova-secrets
  # Internal K8s DNS for service-to-service communication
  notificationServiceHost: notification-service
  notificationServicePort: "8004"
