namespace: prod

config:
  NODE_ENV: "production"
  AUTH_PORT: "8001"
  PRODUCT_PORT: "8002"
  ORDER_PORT: "8003"
  NOTIFICATION_PORT: "8004"
  FRONTEND_PORT: "8080"
  NOTIFICATION_SERVICE_HOST: "notification-service"
  NOTIFICATION_SERVICE_PORT: "8004"

secrets:
  AUTH_MONGO_URI: "REPLACE_ME"
  PRODUCT_MONGO_URI: "REPLACE_ME"
  ORDER_MONGO_URI: "REPLACE_ME"
  JWT_SECRET: "REPLACE_ME"
  EMAIL_USER: "REPLACE_ME"
  EMAIL_PASS: "REPLACE_ME"
