namespace: prod

scheme: internet-facing

targetType: ip

routes:
  frontend:
    serviceName: frontend-service
    servicePort: 8080
    path: /
  auth:
    serviceName: auth-service
    servicePort: 8001
    path: /api/auth
  product:
    serviceName: product-service
    servicePort: 8002
    path: /api/products
  order:
    serviceName: order-service
    servicePort: 8003
    path: /api/orders
