apiVersion: v1
kind: Secret
metadata:
  name: shopnova-secrets
  namespace: prod
type: Opaque
stringData:
  AUTH_MONGO_URI: "mongodb://mongo:27017/authdb"
  PRODUCT_MONGO_URI: "mongodb://mongo:27017/productdb"
  ORDER_MONGO_URI: "mongodb://mongo:27017/orderdb"
  JWT_SECRET: "s8fK2#xP9Lm!qZr@8uV1bY"
  EMAIL_USER: "abnvb38@gmail.com"
  EMAIL_PASS: "vbzs mxri bblb oqir"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/692828329130/shopnova-notification-queue"