apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnova-alb-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: shopnova
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.targetType }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: {{ .Values.routes.auth.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.routes.auth.serviceName }}
                port:
                  number: {{ .Values.routes.auth.servicePort }}
          - path: {{ .Values.routes.product.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.routes.product.serviceName }}
                port:
                  number: {{ .Values.routes.product.servicePort }}
          - path: {{ .Values.routes.order.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.routes.order.serviceName }}
                port:
                  number: {{ .Values.routes.order.servicePort }}
          - path: {{ .Values.routes.frontend.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.routes.frontend.serviceName }}
                port:
                  number: {{ .Values.routes.frontend.servicePort }}
