namespace: prod

image:
  repository: abhinavbabu33/new-shopnova-notification-2
  tag: latest
  pullPolicy: Always

replicaCount: 1

port: 8004

resources:
  requests:
    cpu: 64m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  configMapName: shopnova-config
  secretName: shopnova-secrets
