namespace: prod

image:
  repository: abhinavbabu33/new-shopnova-product
  tag: latest
  pullPolicy: Always

replicaCount: 1

port: 8002

resources:
  requests:
    cpu: 128m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  nodeEnv: production
  configMapName: shopnova-config
  secretName: shopnova-secrets
